### ISSUE TITLE
Empty annotation bug in transforms.

### ISSUE THREAD

**Issue by Dafidofff** [NKI-AI/dlup#106]
**Describe the bug**
In transforms there is checked for empty annotations via 
```
if "annotations" not in sample:
    return sample
```
However, dlup concat dataset returns an empty list when no annotations are present, so this check will never be called. Should be changed to the following check:
```
if sample.get(annotations, None):
    return sample
```

**To Reproduce**
```
ds = TiledROIsSlideImageDataset.from_standard_tiling(
                image_path,
                mpp=2.0,
                tile_size=256,
                tile_overlap=64,
                tile_mode=TilingMode.Overflow,
                rois=rois,
                crop=False,
                mask=None,
                annotations=[],
                transform=ContainsPolygonToLabel(roi_name="roi", label="tumor", threshold=0.4),
                backend=ImageBackend.PYVIPS,
            )
```

**Expected behavior**
Should not apply transform when no annotations are present. 

**Environment**
dlup version: 3.3.4
How installed: pypi
Python version: 3.8.13
Operating System: Debian GNU/Linux 11

**Comment by jonasteuwen** [comment]
Why not set annotations to None?

**Comment by Dafidofff** [comment]
Yes! Jonas solved it already!
