### ISSUE TITLE
Feat: Add warning about `multiprocessing` context when using `TifffileImageWriter.from_tiles_iterator`

### ISSUE THREAD

**Issue by YoniSchirris** [NKI-AI/dlup#124]
**Is your feature request related to a problem? Please describe.**
When the `tiles_iterator` passed to `TifffileImageWriter.from_tiles_iterator` is a `torch.data.DataLoader` with `num_workers>0` and the `multiprocessing.context` is `fork` (default on Linux), the locked writing thread may be copied by the `fork`ed process and will freeze the code unexpectedly.

However, this can be solved by explicitly setting the `multiprocessing.context`, with, e.g., 
```
import multiprocessing
try:
    multiprocessing.set_start_method('spawn', force=True)  # I noticed that without `force=True` it would give a `RuntimeError` as the context was supposedly already set.
except RuntimeError as e:  # The force may not work? If not, we want to throw an error, because i don't want frozen code
    raise e
```

**Describe the solution you'd like**
Minimum solution I could think of is throwing a warning to `stdout` if 
1) the `multiprocessing.context` is `fork`

But this may be too generic, as this doesn't pose a problem when the iterator is not multithreaded.

So preferably we also check if
2) the iterator is multithreaded.

Point 2 may be difficult, though, since it accept a generic iterator. 

A possible way of doing this could be to
1) See if `torch` can be imported
2) If it is, we can see if the provided `iterator` is a `torch.data.DataLoader` under the hood, and if so, check the `num_workers`. And if `num_workers>0` we throw a warning.

**Describe alternatives you've considered**
- Add it to the documentation of https://docs.aiforoncology.nl/dlup/writers.html. 
- Add to the examples of https://docs.aiforoncology.nl/dlup/examples.html a real-world examples with multithreaded iterators and setting the context

**Additional context**
https://pythonspeed.com/articles/python-multiprocessing/

**Comment by YoniSchirris** [comment]
Another way to do it is to create some generic `DlupIterator` class that can use a `torch.data.DataLoader` backend or a simply `yield` backend with a `apply_fn: Callable` argument might you need to do something to the result of the `DLUPDataset` class

**Comment by jonasteuwen** [comment]
Hi @YoniSchirris I would propose to add this to the documentation of dlup, rather than implementing a warning explicitly, as the idea of `dlup` is to keep it independent of any DL framework.
