### ISSUE TITLE
Different grids for TiledROIsSlideImageDataset

### ISSUE THREAD

**Issue by manyids2** [NKI-AI/dlup#125]
**Is your feature request related to a problem? Please describe.**
I need to implement custom grids to retrieve entire regions, or tiled regions. 

**Describe the solution you'd like**
Methods similar `from_standard_tiling`   like `from_regions` and `from_tiled_regions` `from_aligned_grids` ( which is for multiscale ).

**Describe alternatives you've considered**
Just make the grids myself. e.g.
```
def get_regions_grids(rois: _rois_type, mpp: float, slide_mpp: float) -> _grids_type:
    """Grids for rois. One 'tile' for each region, each with different size, at given mpp."""
    grids = []
    scaling = slide_mpp / mpp
    for offset, size in rois:
        offset = tuple(np.ceil(np.asarray(offset) * scaling).astype(int))
        size = tuple(np.floor(np.asarray(size) * scaling).astype(int))
        grid = Grid.from_tiling(
            offset,
            size=size,
            tile_size=size,
            tile_overlap=(0, 0),
        )
        grids.append((grid, size, mpp))

    return grids
```

**Additional context**

**Comment by sinberlin2** [comment]
the use cases that I have are:

- construct a dataset from images and associated regions (that need not be tiled): I am currently doing this by using SlideImageDatasetBase 

- construct a dataset from larger ROIs that should be tiled into subregions (tile size could be made dependent on ROI size or fixed)
