### ISSUE TITLE
Feat: use `openslide.bounds-{}` if available

### ISSUE THREAD

**Issue by YoniSchirris** [NKI-AI/dlup#135]
**Is your feature request related to a problem? Please describe.**
We have encountered `.mrxs` files that are extraordinarily large. The majority of the slide is random background, and only 10% of is the actual glass slide (of which then ~50% is covered by tissue).

**Describe the solution you'd like**
If there is information available that states which portion of the WSI contains the glass slide, create a dataset using these bounds by default. Read only the region `(x1=openslide.bounds-x, x2=openslide.bounds-x+openslide.bounds-width, y1=openslide.bounds-y, y2=openslide.bounds-y+openslide.bounds-height)`

**Describe alternatives you've considered**
Run tissue segmentation on entire slide, requiring much more compute.

**Additional context**
- Think about: Resulting segmentation tiffs; write the background as an "ignore" class, or only write a tiff that is the `height` and `width` of the `openslide.bounds-height` and `openslide.bounds-width`?
- DeepZoom does this already

**Comment by YoniSchirris** [comment]
I have implemented this myself. 
- Write the ROI size to TIFF
- add metadata about ROI size, mpp, and location
- When loading such a mask, place it back into an empty array at the right location and it can be used as a background mask on a whole-slide image.

@jonasteuwen lmk if this is a generic enough use case to be worth an additional feature

**Comment by jonasteuwen** [comment]
Is implemented in #146.
