### ISSUE TITLE
Annotations made by HALO for mrxs slide are not read correctly due to limit bounds

### ISSUE THREAD

**Issue by moerlemans** [NKI-AI/dlup#160]
**Describe the bug**
When loading an mrxs slide with limit_bounds true and an annotation with the TiledROIDataset.from_standard_tiling. It will not produce the correct annotations, but annotations at an offset equal to the limit bounds as HALO annotations are apperently not taking limit bounds into account in their coordinates.

**To Reproduce**
A clear and concise description on how to reproduce the problem.
Load slide image and halo annotation using the WsiAnnotations.from_halo_xml and make a dataset using TiledROIsSlideImageDataset.from_standard_tiling with limit_bounds=True. Visualize to check.

**Expected behavior**
Expect the annotations to be returned in the good coordinate system in which the images are as well.

**Environment**
dlup version: 0.3.25
How installed: pip install -e .
Python version: 3.10
Operating System:

**Additional context**

**Comment by jonasteuwen** [comment]
This is probably fixes, depends on upstream changes to pyhaloxml.

**Comment by rharkes** [comment]
Not in this case. The offsets are in the .mrxs file and need to be used to translate all the annotations. We have the same problem in QuPath, where I fixed it at the import stage. Sadly the .annotation files do not contain any option for global offset.

**Comment by jonasteuwen** [comment]
@rharkes I think this is fixed now by offsetting in the reader

**Comment by rharkes** [comment]
Good. I remembered it was a pretty annoying problem. When we thought it was fixed, the offset turned out to always be a multiple of 256. Even though the values in the mrxs data were not.

**Comment by jonasteuwen** [comment]
That’s good to know!
