### ISSUE TITLE
Inconsistent MPP in output of get_mask function

### ISSUE THREAD

**Issue by BPdeRooij** [NKI-AI/dlup#171]
**Describe the bug**
When generating a binary tissue mask with the `get_mask` function, the output mpp is not consistent because of the `next_power_of_2` call. [Found here](https://github.com/NKI-AI/dlup/blob/adc6f1196bc98e4d9dab5e8b62cc048afe08bb49/dlup/background_deprecated.py#L221C21-L221C36)

**To Reproduce**
Create a SlideImage using `CMU-1.tiff` from [here](https://qupath.readthedocs.io/en/0.4/docs/intro/acknowledgements.html), call `get_mask` on it. The resulting MPP of the image is ~5.6 
```
path = 'path/to/CMU-1.tiff'
slide = SlideImage.from_file_path(path)
mask = get_mask(slide)
print(f"Resulting mpp: {(np.asarray(slide.size) * slide.mpp) / np.asarray(mask.shape)[::-1]}")
```

**Expected behavior**
The output of the binary mask should be roughly 10 mpp. Removing the `next_power_of_2` call will give the correct mpp. A consistent MPP is desirable for post-processing of mask (e.g. removing small objects with certain area in pixels.)

**Environment**
dlup version: 0.3.27
How installed: pip
Python version: 3.10
Operating System: mac

**Comment by jonasteuwen** [comment]
Thanks @BPdeRooij. This indeed looks like a bug but the function is deprecated for v1.0 (#170). Soon we will have [ahcore](https://github.com/NKI-AI/ahcore) with trained weights that can output masks. Would that solve the problem too?

**Comment by BPdeRooij** [comment]
If the function is deprecated for v1.0, this is not really an issue. However, I think that including a similar function as `get_mask` in DLUP would be good. This would keep DLUP framework-agnostic from any deep learning framework. 

For instance, a user might want to utilize DLUP solely for tiling of a WSI dataset without the need to install additional dependencies, such as ahcore. Having a way to generate a binary tissue mask using DLUP would be a useful feature in that case. 

I'm curious about your thoughts on this, but as far as the original bug is concerned, we can consider closing this thread.

**Comment by jonasteuwen** [comment]
We can make it dependent on jitted models instead. That would keep it framework agnostic.
