### ISSUE TITLE
Can we have `WsiAnnotations.get_scaled_view(scaling)`? 

### ISSUE THREAD

**Issue by AjeyPaiK** [NKI-AI/dlup#175]
Since the annotations for our images can be generated at arbitrary resolutions (ex: from the outputs of a deep learning model), it might be a useful to have:

1. A feature that generates a scaled view of the annotations for a given scaling parameter.
2. A feature that generates the necessary scaling for a given target_mpp.

Currently, if I need to scale annotations stored as geojson objects, I need to execute the following methods repeatedly. 

```
slide_image = SlideImage.from_file_path(image)
slide_mask = SlideImage.from_file_path(mask_path) # Assuming that the masks are stored as tiff files
scaling = slide_mask.get_scaling(slide_image.mpp) # This is a property of SlideImage and not WsiAnnotations
scaled_image_size = slide_mask.get_scaled_size(scaling) # This is a property of SlideImage and not WsiAnnotations
scaled_mask = slide_mask.read_region((0, 0), scaling=scaling, size=scaled_image_size)
```

Can this be implemented as a member function under WsiAnnotations?

**Comment by jonasteuwen** [comment]
That's a great idea. Can you propose a design?

**Comment by AjeyPaiK** [comment]
That's true. Since it's unknown at what mpp the annotations were generated, we can at least think about `get_scaled_view()`

Something like the following:

```
slide_image = SlideImage.from_file_path(image)
scaling = slide_image.get_scaling(target_mpp) # target_mpp should be user defined.
slide_annotations = WsiAnnotations.from_geojson(mask_path) # Assuming that the masks are stored as geojson files.
scaled_slide_annotations = slide_annotations.get_scaled_view(scaling=scaling, region_size=slide_image.size)
```

And, the function can look like this:

```
def get_scaled_view(self, scaling, region_size) -> list[Polygon | Point]:
    return self.read_region((0,0), scaling=scaling, region_size=region_size)
```

Let me know what you think.

**Comment by AjeyPaiK** [comment]
Changed the issue requesting one feature instead of two. `get_scaling()` can be done with the properties of `SlideImage` and hence, it's redundant to implement in `WsiAnnotations()`

**Comment by jonasteuwen** [comment]
@AjeyPaiK Can you implement the same as it's implemented with `_image.py`?
