### ISSUE TITLE
Axes swapped when using Image backend TIFFfile

### ISSUE THREAD

**Issue by sinberlin2** [NKI-AI/dlup#187]
**Describe the bug**
Tiles are sampled outside WSI bounds, causing an error. 'Requested region outside level boundaries'. This is due to axes being in the opposite order when reading in the mask using the Imagebackend TIFFfile as opposed to using ImageBackend PYVIPS.
So as an example:
self._wsi.slide_bounds (in _image.py)
Pyvips backend:
((0, 0), (3758, 2402))
Tifffile backend:
((0, 0), (2402, 3758))

**To Reproduce**
The issue occurs when creating a tiledroidataset from a wsi and a corresponding mask, where the mask is read in with the ImageBackened TIFFfile. 

**Expected behavior**
The mask boundaries should be the same no matter whether it is read using ImageBackend TIFFfile or PYVIPS.

**Environment**
dlup version:
How installed:
Python version:
Operating System:

**Additional context**

**Comment by jonasteuwen** [comment]
Hi! Can you check the behavior as well using openslide as backend?

**Comment by jonasteuwen** [comment]
I looked at it in a bit more detail, and it's called here: https://github.com/NKI-AI/dlup/blob/3271be1ad39c7570a03d5e633ea8effab55dbd51/dlup/backends/common.py#L171

So I would assume that more axis are swapped in the tiffbackend. Before we fix this, we should merge #185
