### ISSUE TITLE
Docs should be improved

### ISSUE THREAD

**Issue by moerlemans** [NKI-AI/dlup#202]
Notes of what should at least happen:

Per section:

1. Installation:
- Are openslide and pixman still necessary? What versions?

2. Quick start:
- Is the python section up to date?
- Layout can be improved

3. Tiling:
- Should be extended
- Crop is not explained well enough
- python examples
- more options can be discussed

4. Writers:
- update examples

5. Backends:
- Is this complete?
- Explanations can be improved upon
- Tips on when to use what backend should be added

6. CL tools:
- Should be extended
- Give concrete examples

7. Examples:
- Can be full of common use cases (maybe rename as well)
- Structure can be better (also clearer navigation)
- update and extend

8. Contributing:
- maybe update, but looks pretty complete

9. dlup:
- update

**Comment by kirbyju** [comment]
I just heard about this project.  Looks very interesting!  If you're trying to setup improved docs with notebooks that demonstrate using real data feel free to take advantage of all the open-access data we've published on The Cancer Imaging Archive.  There's a list of our image collections at https://www.cancerimagingarchive.net/browse-collections/ and you can use the filter at the top of the table to look specifically for pathology datasets.  You can also use the steps outlined in https://github.com/kirbyju/TCIA_Notebooks/blob/main/TCIA_Aspera_CLI_Downloads.ipynb as a way to easily download our pathology datasets via CLI or a notebook.  Should you decide to build any such tutorials using your tools with our data please let me know and I'd be happy to help you advertise them!
