### ISSUE TITLE
Design new multiscale dataset

### ISSUE THREAD

**Issue by jonasteuwen** [NKI-AI/dlup#210]
**Is your feature request related to a problem? Please describe.**
Currently an untested multiscale dataset is available. This should be removed, and after v1.0 a new one should be added if we wish to have such models.

**Describe the solution you'd like**
MultiScaleTiledWsiDataset

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by sinberlin2** [comment]
I would like to use this feature. It would be important to return the mpp with the tile. For sampling from different resolutions equally, it would be useful to be able to access the number of tiles at each resolution.
