### ISSUE TITLE
Custom properties for bounding boxes in GeoJSON

### ISSUE THREAD

**Issue by BPdeRooij** [NKI-AI/dlup#217]
**Is your feature request related to a problem? Please describe.**
Bounding boxes are supported by DLUP and are internally represented as Polygons. There is no easy way of reading bounding boxes from GeoJSONs because the [shape function](https://github.com/NKI-AI/dlup/blob/3109cfbcfd79d625a0c9b1ef37dfa525d496eb65/dlup/annotations.py#L203) never returns a `AnnotationType.BOX`.

**Describe the solution you'd like**
Exporting and reading of annotations with `AnnotationType.BOX` should be possible. Adding a custom property for `Feature object` in the GeoJSON would be a good solution. I believe this is also suggested in the [Feature Object documentation](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2).

**Describe alternatives you've considered**
[On this branch](https://github.com/NKI-AI/dlup/compare/main...feature/extend-annotation-conversion) I have experimented with including a custom property `CastToAnnotationTypeBox` for bounding boxes.

**Additional context**
GeoJSON objects may have a property [bbox](https://datatracker.ietf.org/doc/html/rfc7946#section-5). This should be kept in mind to avoid confusion.
`properties` can also include other features, such as colors ([Issue #154](https://github.com/NKI-AI/dlup/issues/154)) or annotation ontology.

**Comment by BPdeRooij** [comment]
In the definition of the [`Feature object`](https://datatracker.ietf.org/doc/html/rfc7946#section-3.2) it states: 

> A Feature object has a member with the name "properties".  The value of the properties member is an object (any JSON object or a JSON null value).

An example of this is given in the [GeoJSON `FeatureCollection` example](https://datatracker.ietf.org/doc/html/rfc7946#section-1.5).

It seems that QuPath checks some properties when importing annotations to convert to their `Rectangle` annotation (i.e. a Polgyons with a length of 5 and and square corners). It will ignore any `properties` for the object that it does not recognize. This means that the suggested implementation does not interfere with importing annotations into QuPath. 

`AnnotationType.BOX` is only used in specific cases and it is not always wanted to cast a rectangular Polgyon to this datatype. Simply converting every Polygon of length 5 with squared corners will lead to unintended behavior. Having a custom property, such as `DLUP_CastToAnnotationTypeBox`, will avoid these errors.

**Comment by jonasteuwen** [comment]
That’s a great solution, but I would still additionally add this to the constructor, as we might want to load QuPath GeoJSON objects.
