### ISSUE TITLE
If there are multiple polygons in the WsiAnnotation dlup now takes the sum of the area's

### ISSUE THREAD

**Issue by moerlemans** [NKI-AI/dlup#222]
**Problem**
At https://github.com/NKI-AI/dlup/blob/3509bc990595991a5b7ab5801ef07838e2eaf9b0/dlup/background.py#L75 the area of all the polygons inside the region are summed. However, this doesn't consider overlapping annotations and also doesn't consider labels. I have multiple labels in my file (and thus in my WsiAnnotation) e.g. tissue, stroma, dcis ducts and I want to use the tissue label as a mask.

**To reproduce:**
Use latest dlup with a WsiAnnotation with multiple overlapping labels

**Possible fix:**
Allow for a mask_label to be specified in the is_foreground and TiledWsiDataset 
OR
Let WsiAnnotations have a specific property for each SingleAnnotationWrapper which is a boolean if it should be used in the mask or not

Note that both fixed do not stop possible overlapping labels and thus total_area / region_area could still end up bigger than 1.0

**Comment by jonasteuwen** [comment]
You must provide the annotations you’re interested in. Say if it’s a ROI you filter those out and provide that. Be aware that this is for the mask, not the annotations, so what you provide is likely different. Check how ahcore does it.

**Comment by moerlemans** [comment]
This can be fixed by using the filter option on an WsiAnnotation
