### ISSUE TITLE
Multiple holes in annotations are not read correctly

### ISSUE THREAD

**Issue by moerlemans** [NKI-AI/dlup#223]
**Issue**
See https://github.com/NKI-AI/dlup/blob/3509bc990595991a5b7ab5801ef07838e2eaf9b0/dlup/annotations.py#L229. When loading annotations with multiple holes the holes can be of different number of point and therefore casting them to a numpy array doesn't work. 

**Reproduce**
Load any annotations with multiple holes

![image](https://github.com/NKI-AI/dlup/assets/82031608/296ea54e-3791-4c96-bc36-6e60ea3bd5e4)

**Comment by jonasteuwen** [comment]
I think this will be fixed in #228. Can you verify?

**Comment by jonasteuwen** [comment]
Addressed in #228

**Comment by jonasteuwen** [comment]
This is solved in branch #feature-geometry
