### ISSUE TITLE
z-index is not imported or exported with GeoJSONs

### ISSUE THREAD

**Issue by BPdeRooij** [NKI-AI/dlup#240]
**Describe the bug**
The z-index is not taken into account when importing or exporting annotations with GeoJSON.

**To Reproduce**
Create a `WsiAnnotations` object containing annotations with z-indices. Calling `WsiAnnotations.as_geojson()` fails to export z-index of the annotations. When importing annotations with `WsiAnnotations.from_geojson()`, z-index is also ignored.

**Expected behavior**
`WsiAnnotations.as_geojson`, `WsiAnnotations.from_geojson` and `_geometry_to_geojson` should all be able to handle annotations with z-indices correctly.

Environment
dlup version: 0.5.1
How installed: installed from main branch
Python version: 3.10
Operating System: Linux

**Additional context**
A working fix can be found in [this branch](https://github.com/NKI-AI/dlup/tree/feature/extend-dunder-methods).

**Comment by jonasteuwen** [comment]
I don't think it's an issue as the export should export it without needing to sort again, the output itself is already sorted, in the GeoJSON order. There is a test that checks if reading back gives the same result

**Comment by BPdeRooij** [comment]
The annotations are outputted in the correct order, but information is lost in the process. Including the z-index in the GeoJSON properties when exporting (or importing) would not break GeoJSON conventions and would ensure that all information is preserved. I believe it would be useful to include the z-index for completeness and reproducibility.
