### ISSUE TITLE
Shapely upstream change in srtree breaks annotations read_region()

### ISSUE THREAD

**Issue by Tkootstra** [NKI-AI/dlup#78]
**Describe the bug**
Since shapely main branch commit 9b3fa0ae3dfa802a56bb01b21ccf8411a20d5a9d, the implementation of SRTree has changed. the query() method now does not return the Polygons, instead it returns a numpy array with the indices of the tree where the geometries can be found.

**To Reproduce**
install shapely after the mentioned commit with the latest version of dlup

**Expected behavior**
self._annotation_trees[k].query(query_box) should return geometries, but returns indices

**Environment**
dlup version:
How installed:
Python version:
Operating System:

**Additional context**

**Comment by jonasteuwen** [comment]
@Tkootstra This was fixed, correct?

**Comment by Tkootstra** [comment]
Yes. This was fixed with the PR I made
